name: CI
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'The tag of the image to use for the container'
        required: false
        default: ''

jobs:
  integration-test-in-studio-container:
    uses: PickNikRobotics/moveit_pro_ci/.github/workflows/workspace_integration_test.yaml@01ac7e19a9e4eeeff4965556e2be37159025e893 # v0.0.8
    with:
      image_tag: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref || github.ref_name }}
      colcon_test_args: "--executor sequential --packages-select cybertech_hw cybertech_mock"
      runner: "picknik-16-amd64"
    secrets:
      moveit_license_key: ${{ secrets.STUDIO_CI_LICENSE_KEY }}

  ensure-no-ssh-in-gitmodules:
    name: Ensure no SSH URLs in .gitmodules
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Check .gitmodules file for Git-over-SSH URLs
        run: "! grep 'git@' .gitmodules"

  validate_objectives:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: PickNikRobotics/moveit_pro_lint@v0.0.1
